x-zane-env:
  main_domain: "{{ generate_domain }}"
  IMAGE_VERSION: "2.38.1-alpine"

services:
  portainer:
    image: portainer/portainer-ce:${IMAGE_VERSION}
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-data:/data
    deploy:
      labels:
        zane.http.routes.0.port: 9000
        zane.http.routes.0.domain: ${main_domain}

volumes:
  portainer-data:
