version: "3.8"
x-zane-env:
  main_domain: "{{ generate_domain }}"
  SUPERUSER_PASSWORD: "{{ generate_password | 12 }}"
  POSTGRES_USER: bugsinkuser
  POSTGRES_PASSWORD: "{{ generate_password | 32 }}"
  POSTGRES_DB: bugsink
  SECRET_KEY: "{{ generate_password | 64 }}"
  CREATE_SUPERUSER: admin:${SUPERUSER_PASSWORD}
  BEHIND_HTTPS_PROXY: "true"
  BASE_URL: https://${main_domain} # ot http://${main_domain}
  IMAGE_VERSION: 2.0.13

services:
  db:
    image: postgres:17-alpine
    restart: unless-stopped
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    volumes:
      - type: volume
        target: /var/lib/postgresql/data
        source: db-data
    healthcheck:
      test:
        - CMD-SHELL
        - pg_isready -h localhost -U ${POSTGRES_USER}
      retries: 5
      start_period: 10s
      interval: 5s
      timeout: 5s
  web:
    image: bugsink/bugsink:${IMAGE_VERSION:-latest}
    depends_on:
      - db
    environment:
      SECRET_KEY: ${SECRET_KEY}
      CREATE_SUPERUSER: ${CREATE_SUPERUSER}
      PORT: "8000"
      DATABASE_URL: postgresql://${POSTGRES_USER}:${POSTGRES_PASSWORD}@db:5432/${POSTGRES_DB}
      BEHIND_HTTPS_PROXY: ${BEHIND_HTTPS_PROXY}
      BASE_URL: ${BASE_URL}
    healthcheck:
      test:
        - CMD-SHELL
        - python -c 'import requests; requests.get("http://localhost:8000/").raise_for_status()'
      interval: 5s
      timeout: 20s
      retries: 10
    deploy:
      labels:
        zane.http.routes.0.domain: ${main_domain}
        zane.http.routes.0.port: 8000

volumes:
  db-data:
